# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 851d1b43cd5a82482307c15566433a6cc852b6513d03b5fc13db5328e531675ca5538dccb193ccfc087d9f7c75b6381d779d1f569089be1ca469459814d47c18

test:
  secret_key_base: c0e646328ce7626cd933b88eb6795a43438129772327a51c583bb04076a0a841b82f0b2e70dd8908186d8eaf57c7746b003c31254554b76d66e0c2da016f24f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
